Traceback (most recent call last):
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Boundary Variables (auxiliary coordinates)
arr_time_bnd = np.column_stack((arr_time - 15, arr_time + 15))
arr_lat_bnd = np.column_stack((arr_lat - 0.5, arr_lat + 0.5))
arr_lon_bnd = np.column_stack((arr_lon - 1, arr_lon + 1))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[11], line 2[0m
[1;32m      1[0m [38;5;66;03m# Boundary Variables (auxiliary coordinates)[39;00m
[0;32m----> 2[0m arr_time_bnd [38;5;241m=[39m np[38;5;241m.[39mcolumn_stack(([43marr_time[49m[43m [49m[38;5;241;43m-[39;49m[43m [49m[38;5;241;43m15[39;49m, arr_time [38;5;241m+[39m [38;5;241m15[39m))
[1;32m      3[0m arr_lat_bnd [38;5;241m=[39m np[38;5;241m.[39mcolumn_stack((arr_lat [38;5;241m-[39m [38;5;241m0.5[39m, arr_lat [38;5;241m+[39m [38;5;241m0.5[39m))
[1;32m      4[0m arr_lon_bnd [38;5;241m=[39m np[38;5;241m.[39mcolumn_stack((arr_lon [38;5;241m-[39m [38;5;241m1[39m, arr_lon [38;5;241m+[39m [38;5;241m1[39m))

[0;31mTypeError[0m: unsupported operand type(s) for -: 'cftime._cftime.Datetime360Day' and 'int'

